/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_project_Adapter */

#ifndef _Included_com_example_project_Adapter
#define _Included_com_example_project_Adapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_project_Adapter
 * Method:    jniCppAnimal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_project_Adapter_jniCppAnimal
  (JNIEnv *, jobject);

/*
 * Class:     com_example_project_Adapter
 * Method:    jniRustCountry
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_project_Adapter_jniRustCountry
  (JNIEnv *, jobject);

/*
 * Class:     com_example_project_Adapter
 * Method:    jniRustCallCppOs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_project_Adapter_jniRustCallCppOs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
