
cc_library(
    name = "sub2_sample",
    srcs = [
        "sub_sample.cpp",
        "sub_sample.h",
    ],
    hdrs = ["sub_sample.h"],
    visibility = ["//visibility:public"],
    deps = [],
    linkstatic = 1,
)
