/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_project_Loader */

#ifndef _Included_com_example_project_Loader
#define _Included_com_example_project_Loader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_project_Loader
 * Method:    jniTest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_project_Loader_jniTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
